

---
- name: Pull Docker Image of Calculator
  hosts: all
  tasks:
    - name: Pull calculator.Calculator Image from Docker Hub
      docker_image:
        name: pragyak26/calculator-devops
        source: pull